#!/bin/sh
# lattice_init.sh -- generated by Slot4096 resonance engine
# Every parameter below was derived from the live phi-lattice state.
# This script IS the OS boot sequence.

# -- 1. Entropy: feed all 4096 slot values into /dev/urandom --
if [ -f '/lattice/entropy.bin' ]; then
  dd if='/lattice/entropy.bin' of=/dev/urandom bs=4096 2>/dev/null
  echo "[lattice] Entropy: $(wc -c < '/lattice/entropy.bin') bytes -> /dev/urandom"
fi

# -- 1b. Kernel sysctl: slots[23..30] -> /etc/sysctl.d/99-lattice.conf --
mkdir -p /etc/sysctl.d
cat > /etc/sysctl.d/99-lattice.conf << 'EOSYSCTL'
vm.swappiness = 0
kernel.pid_max = 32768
vm.dirty_ratio = 5
net.core.somaxconn = 128
kernel.sched_min_granularity_ns = 100000
kernel.randomize_va_space = 0
net.ipv4.tcp_rmem = 4096 4096 16777216
net.ipv4.tcp_wmem = 4096 4096 16777216
EOSYSCTL
sysctl -w vm.swappiness=0 2>/dev/null              && echo '[lattice] vm.swappiness=0'
sysctl -w kernel.pid_max=32768 2>/dev/null             && echo '[lattice] kernel.pid_max=32768'
sysctl -w vm.dirty_ratio=5 2>/dev/null             && echo '[lattice] vm.dirty_ratio=5'
sysctl -w net.core.somaxconn=128 2>/dev/null         && echo '[lattice] net.core.somaxconn=128'
sysctl -w kernel.sched_min_granularity_ns=100000 2>/dev/null && echo '[lattice] sched_gran=100000ns'
sysctl -w kernel.randomize_va_space=0 2>/dev/null  && echo '[lattice] aslr=0'
sysctl -w net.ipv4.tcp_rmem='4096 4096 16777216' 2>/dev/null && echo '[lattice] tcp_rmem=4096'
sysctl -w net.ipv4.tcp_wmem='4096 4096 16777216' 2>/dev/null && echo '[lattice] tcp_wmem=4096'

# -- 1c. ramfs: /run/lattice -> in-memory lattice state for all processes --
mkdir -p /run/lattice
mount -t ramfs -o size=1m ramfs /run/lattice 2>/dev/null
{
echo 'LATTICE_SEED=0xba8ddca35827e77f'
echo 'LATTICE_N=4096'
echo 'LATTICE_STEPS=0'
echo 'LATTICE_HOST=phi4096-00000000'
echo 'LATTICE_SWAPPINESS=0'
echo 'LATTICE_PID_MAX=32768'
echo 'LATTICE_DIRTY_RATIO=5'
echo 'LATTICE_SOMAXCONN=128'
echo 'LATTICE_SCHED_GRAN=100000'
echo 'LATTICE_ASLR=0'
echo 'LATTICE_TCP_RMEM=4096'
echo 'LATTICE_TCP_WMEM=4096'
} > /run/lattice/state
chmod 444 /run/lattice/state
echo '[lattice] /run/lattice (ramfs) mounted — phi-field state live'

# -- 2. Hostname (phi-fold of slots[0..3]) --
hostname 'phi4096-00000000'
echo 'phi4096-00000000' > /etc/hostname
echo '[lattice] Hostname:  phi4096-00000000'

# -- 3. Timezone (slot[16] -> Etc/GMT+11) --
ln -sf /usr/share/zoneinfo/Etc/GMT+11 /etc/localtime 2>/dev/null
echo 'Etc/GMT+11' > /etc/timezone
echo '[lattice] Timezone:  Etc/GMT+11'

# -- 4. APK mirror (slot[4] -> dl-cdn.alpinelinux.org) --
cat > /etc/apk/repositories << 'EOAPK'
https://dl-cdn.alpinelinux.org/alpine/latest-stable/main
https://dl-cdn.alpinelinux.org/alpine/latest-stable/community
EOAPK
echo '[lattice] APK mirror: dl-cdn.alpinelinux.org'

# -- 5. Packages (slots[5..15] bit-select) --
echo '[lattice] Installing:  curl bash'
apk update -q 2>/dev/null && apk add -q  curl bash 2>/dev/null
echo '[lattice] Packages ready.'

# -- 6. Process priority (slot[17] -> nice -20) --
renice -20 $$ >/dev/null 2>&1
echo '[lattice] Nice: -20'

# -- 7. slot4096 user (slot[18] -> UID 1000) --
addgroup -g 1000 slot4096 2>/dev/null
adduser -u 1000 -G slot4096 -h /home/slot4096 -s /bin/bash -D slot4096 2>/dev/null
mkdir -p /home/slot4096
chown slot4096:slot4096 /home/slot4096
echo '[lattice] User: slot4096 uid=1000'

# -- 8. Profile: export LATTICE_* + ulimit/umask to all shells --
mkdir -p /etc/profile.d
cat > /etc/profile.d/lattice.sh << 'EOPROFILE'
export LATTICE_N=4096
export LATTICE_STEPS=0
export LATTICE_SEED=0xba8ddca35827e77f
export LATTICE_HOSTNAME=phi4096-00000000
export LATTICE_MIRROR=dl-cdn.alpinelinux.org
export LATTICE_TZ=Etc/GMT+11
export LATTICE_NICE=-20
export LATTICE_UID=1000
export LATTICE_NOFILE=1024
export LATTICE_UMASK=0002
export LATTICE_HISTSIZE=500
export LATTICE_TMOUT=300
export LATTICE_SWAPPINESS=0
export LATTICE_PID_MAX=32768
export LATTICE_DIRTY_RATIO=5
export LATTICE_SOMAXCONN=128
export LATTICE_SCHED_GRAN=100000
export LATTICE_ASLR=0
export LATTICE_TCP_RMEM=4096
export LATTICE_TCP_WMEM=4096
umask 0002
ulimit -n 1024 2>/dev/null
export HISTSIZE=500
export HISTFILESIZE=1000
export TMOUT=300
export PS1='\[\033[1;35m\]slot4096@phi4096-00000000:\[\033[1;32m\]\w\[\033[0m\]$ '
EOPROFILE

# -- 9. ~/.bashrc for slot4096 --
cat > /home/slot4096/.bashrc << 'EOBASHRC'
. /etc/profile.d/lattice.sh
alias ls='ls --color=auto'
alias ll='ls -la'
alias lattice='cat /lattice/state.env'
alias slots='ls /lattice/slots/ | head -32'
alias kern='cat /run/lattice/state'
alias sysctl-lattice='sysctl vm.swappiness kernel.pid_max vm.dirty_ratio net.core.somaxconn kernel.randomize_va_space 2>/dev/null'
export HISTFILE=/home/slot4096/.bash_history
EOBASHRC
cp /home/slot4096/.bashrc /home/slot4096/.bash_profile
chown slot4096:slot4096 /home/slot4096/.bashrc /home/slot4096/.bash_profile
echo '[lattice] ~/.bashrc written for slot4096'

# -- 10. /etc/issue --
printf '\nSlot4096 Lattice-Powered Alpine Linux\n  host: phi4096-00000000  seed: 0xba8ddca35827e77f\n  slots: 4096  steps: 0  nice: -20  uid: 1000\n\n' > /etc/issue
echo '[lattice] /etc/issue written'

# -- 11. /etc/os-release --
cat > /etc/os-release << 'EOOSREL'
NAME="Slot4096 Alpine Linux"
ID=alpine
PRETTY_NAME="Slot4096 Lattice-Powered Alpine Linux"
LATTICE_SEED=0xba8ddca35827e77f
LATTICE_HOST=phi4096-00000000
LATTICE_SLOTS=4096
LATTICE_STEPS=0
EOOSREL
echo '[lattice] /etc/os-release written'

# -- 12. /lattice/slots/ : slot values as files --
mkdir -p /lattice/slots
echo '0.0000000000000000' > /lattice/slots/0
echo '0.0000000000000000' > /lattice/slots/1
echo '0.0000000000000000' > /lattice/slots/2
echo '0.0000000000000000' > /lattice/slots/3
echo '0.0000000000000000' > /lattice/slots/4
echo '0.0000000000000000' > /lattice/slots/5
echo '0.0000000000000000' > /lattice/slots/6
echo '0.0000000000000000' > /lattice/slots/7
echo '0.0000000000000000' > /lattice/slots/8
echo '0.0000000000000000' > /lattice/slots/9
echo '0.0000000000000000' > /lattice/slots/10
echo '0.0000000000000000' > /lattice/slots/11
echo '0.0000000000000000' > /lattice/slots/12
echo '0.0000000000000000' > /lattice/slots/13
echo '0.0000000000000000' > /lattice/slots/14
echo '0.0000000000000000' > /lattice/slots/15
echo '0.0000000000000000' > /lattice/slots/16
echo '0.0000000000000000' > /lattice/slots/17
echo '0.0000000000000000' > /lattice/slots/18
echo '0.0000000000000000' > /lattice/slots/19
echo '0.0000000000000000' > /lattice/slots/20
echo '0.0000000000000000' > /lattice/slots/21
echo '0.0000000000000000' > /lattice/slots/22
echo '0.0000000000000000' > /lattice/slots/23
echo '0.0000000000000000' > /lattice/slots/24
echo '0.0000000000000000' > /lattice/slots/25
echo '0.0000000000000000' > /lattice/slots/26
echo '0.0000000000000000' > /lattice/slots/27
echo '0.0000000000000000' > /lattice/slots/28
echo '0.0000000000000000' > /lattice/slots/29
echo '0.0000000000000000' > /lattice/slots/30
echo '0.0000000000000000' > /lattice/slots/31
echo '0.0000000000000000' > /lattice/slots/32
echo '0.0000000000000000' > /lattice/slots/33
echo '0.0000000000000000' > /lattice/slots/34
echo '0.0000000000000000' > /lattice/slots/35
echo '0.0000000000000000' > /lattice/slots/36
echo '0.0000000000000000' > /lattice/slots/37
echo '0.0000000000000000' > /lattice/slots/38
echo '0.0000000000000000' > /lattice/slots/39
echo '0.0000000000000000' > /lattice/slots/40
echo '0.0000000000000000' > /lattice/slots/41
echo '0.0000000000000000' > /lattice/slots/42
echo '0.0000000000000000' > /lattice/slots/43
echo '0.0000000000000000' > /lattice/slots/44
echo '0.0000000000000000' > /lattice/slots/45
echo '0.0000000000000000' > /lattice/slots/46
echo '0.0000000000000000' > /lattice/slots/47
echo '0.0000000000000000' > /lattice/slots/48
echo '0.0000000000000000' > /lattice/slots/49
echo '0.0000000000000000' > /lattice/slots/50
echo '0.0000000000000000' > /lattice/slots/51
echo '0.0000000000000000' > /lattice/slots/52
echo '0.0000000000000000' > /lattice/slots/53
echo '0.0000000000000000' > /lattice/slots/54
echo '0.0000000000000000' > /lattice/slots/55
echo '0.0000000000000000' > /lattice/slots/56
echo '0.0000000000000000' > /lattice/slots/57
echo '0.0000000000000000' > /lattice/slots/58
echo '0.0000000000000000' > /lattice/slots/59
echo '0.0000000000000000' > /lattice/slots/60
echo '0.0000000000000000' > /lattice/slots/61
echo '0.0000000000000000' > /lattice/slots/62
echo '0.0000000000000000' > /lattice/slots/63
echo '0.0000000000000000' > /lattice/slots/64
echo '0.0000000000000000' > /lattice/slots/65
echo '0.0000000000000000' > /lattice/slots/66
echo '0.0000000000000000' > /lattice/slots/67
echo '0.0000000000000000' > /lattice/slots/68
echo '0.0000000000000000' > /lattice/slots/69
echo '0.0000000000000000' > /lattice/slots/70
echo '0.0000000000000000' > /lattice/slots/71
echo '0.0000000000000000' > /lattice/slots/72
echo '0.0000000000000000' > /lattice/slots/73
echo '0.0000000000000000' > /lattice/slots/74
echo '0.0000000000000000' > /lattice/slots/75
echo '0.0000000000000000' > /lattice/slots/76
echo '0.0000000000000000' > /lattice/slots/77
echo '0.0000000000000000' > /lattice/slots/78
echo '0.0000000000000000' > /lattice/slots/79
echo '0.0000000000000000' > /lattice/slots/80
echo '0.0000000000000000' > /lattice/slots/81
echo '0.0000000000000000' > /lattice/slots/82
echo '0.0000000000000000' > /lattice/slots/83
echo '0.0000000000000000' > /lattice/slots/84
echo '0.0000000000000000' > /lattice/slots/85
echo '0.0000000000000000' > /lattice/slots/86
echo '0.0000000000000000' > /lattice/slots/87
echo '0.0000000000000000' > /lattice/slots/88
echo '0.0000000000000000' > /lattice/slots/89
echo '0.0000000000000000' > /lattice/slots/90
echo '0.0000000000000000' > /lattice/slots/91
echo '0.0000000000000000' > /lattice/slots/92
echo '0.0000000000000000' > /lattice/slots/93
echo '0.0000000000000000' > /lattice/slots/94
echo '0.0000000000000000' > /lattice/slots/95
echo '0.0000000000000000' > /lattice/slots/96
echo '0.0000000000000000' > /lattice/slots/97
echo '0.0000000000000000' > /lattice/slots/98
echo '0.0000000000000000' > /lattice/slots/99
echo '0.0000000000000000' > /lattice/slots/100
echo '0.0000000000000000' > /lattice/slots/101
echo '0.0000000000000000' > /lattice/slots/102
echo '0.0000000000000000' > /lattice/slots/103
echo '0.0000000000000000' > /lattice/slots/104
echo '0.0000000000000000' > /lattice/slots/105
echo '0.0000000000000000' > /lattice/slots/106
echo '0.0000000000000000' > /lattice/slots/107
echo '0.0000000000000000' > /lattice/slots/108
echo '0.0000000000000000' > /lattice/slots/109
echo '0.0000000000000000' > /lattice/slots/110
echo '0.0000000000000000' > /lattice/slots/111
echo '0.0000000000000000' > /lattice/slots/112
echo '0.0000000000000000' > /lattice/slots/113
echo '0.0000000000000000' > /lattice/slots/114
echo '0.0000000000000000' > /lattice/slots/115
echo '0.0000000000000000' > /lattice/slots/116
echo '0.0000000000000000' > /lattice/slots/117
echo '0.0000000000000000' > /lattice/slots/118
echo '0.0000000000000000' > /lattice/slots/119
echo '0.0000000000000000' > /lattice/slots/120
echo '0.0000000000000000' > /lattice/slots/121
echo '0.0000000000000000' > /lattice/slots/122
echo '0.0000000000000000' > /lattice/slots/123
echo '0.0000000000000000' > /lattice/slots/124
echo '0.0000000000000000' > /lattice/slots/125
echo '0.0000000000000000' > /lattice/slots/126
echo '0.0000000000000000' > /lattice/slots/127
echo '0.0000000000000000' > /lattice/slots/128
echo '0.0000000000000000' > /lattice/slots/129
echo '0.0000000000000000' > /lattice/slots/130
echo '0.0000000000000000' > /lattice/slots/131
echo '0.0000000000000000' > /lattice/slots/132
echo '0.0000000000000000' > /lattice/slots/133
echo '0.0000000000000000' > /lattice/slots/134
echo '0.0000000000000000' > /lattice/slots/135
echo '0.0000000000000000' > /lattice/slots/136
echo '0.0000000000000000' > /lattice/slots/137
echo '0.0000000000000000' > /lattice/slots/138
echo '0.0000000000000000' > /lattice/slots/139
echo '0.0000000000000000' > /lattice/slots/140
echo '0.0000000000000000' > /lattice/slots/141
echo '0.0000000000000000' > /lattice/slots/142
echo '0.0000000000000000' > /lattice/slots/143
echo '0.0000000000000000' > /lattice/slots/144
echo '0.0000000000000000' > /lattice/slots/145
echo '0.0000000000000000' > /lattice/slots/146
echo '0.0000000000000000' > /lattice/slots/147
echo '0.0000000000000000' > /lattice/slots/148
echo '0.0000000000000000' > /lattice/slots/149
echo '0.0000000000000000' > /lattice/slots/150
echo '0.0000000000000000' > /lattice/slots/151
echo '0.0000000000000000' > /lattice/slots/152
echo '0.0000000000000000' > /lattice/slots/153
echo '0.0000000000000000' > /lattice/slots/154
echo '0.0000000000000000' > /lattice/slots/155
echo '0.0000000000000000' > /lattice/slots/156
echo '0.0000000000000000' > /lattice/slots/157
echo '0.0000000000000000' > /lattice/slots/158
echo '0.0000000000000000' > /lattice/slots/159
echo '0.0000000000000000' > /lattice/slots/160
echo '0.0000000000000000' > /lattice/slots/161
echo '0.0000000000000000' > /lattice/slots/162
echo '0.0000000000000000' > /lattice/slots/163
echo '0.0000000000000000' > /lattice/slots/164
echo '0.0000000000000000' > /lattice/slots/165
echo '0.0000000000000000' > /lattice/slots/166
echo '0.0000000000000000' > /lattice/slots/167
echo '0.0000000000000000' > /lattice/slots/168
echo '0.0000000000000000' > /lattice/slots/169
echo '0.0000000000000000' > /lattice/slots/170
echo '0.0000000000000000' > /lattice/slots/171
echo '0.0000000000000000' > /lattice/slots/172
echo '0.0000000000000000' > /lattice/slots/173
echo '0.0000000000000000' > /lattice/slots/174
echo '0.0000000000000000' > /lattice/slots/175
echo '0.0000000000000000' > /lattice/slots/176
echo '0.0000000000000000' > /lattice/slots/177
echo '0.0000000000000000' > /lattice/slots/178
echo '0.0000000000000000' > /lattice/slots/179
echo '0.0000000000000000' > /lattice/slots/180
echo '0.0000000000000000' > /lattice/slots/181
echo '0.0000000000000000' > /lattice/slots/182
echo '0.0000000000000000' > /lattice/slots/183
echo '0.0000000000000000' > /lattice/slots/184
echo '0.0000000000000000' > /lattice/slots/185
echo '0.0000000000000000' > /lattice/slots/186
echo '0.0000000000000000' > /lattice/slots/187
echo '0.0000000000000000' > /lattice/slots/188
echo '0.0000000000000000' > /lattice/slots/189
echo '0.0000000000000000' > /lattice/slots/190
echo '0.0000000000000000' > /lattice/slots/191
echo '0.0000000000000000' > /lattice/slots/192
echo '0.0000000000000000' > /lattice/slots/193
echo '0.0000000000000000' > /lattice/slots/194
echo '0.0000000000000000' > /lattice/slots/195
echo '0.0000000000000000' > /lattice/slots/196
echo '0.0000000000000000' > /lattice/slots/197
echo '0.0000000000000000' > /lattice/slots/198
echo '0.0000000000000000' > /lattice/slots/199
echo '0.0000000000000000' > /lattice/slots/200
echo '0.0000000000000000' > /lattice/slots/201
echo '0.0000000000000000' > /lattice/slots/202
echo '0.0000000000000000' > /lattice/slots/203
echo '0.0000000000000000' > /lattice/slots/204
echo '0.0000000000000000' > /lattice/slots/205
echo '0.0000000000000000' > /lattice/slots/206
echo '0.0000000000000000' > /lattice/slots/207
echo '0.0000000000000000' > /lattice/slots/208
echo '0.0000000000000000' > /lattice/slots/209
echo '0.0000000000000000' > /lattice/slots/210
echo '0.0000000000000000' > /lattice/slots/211
echo '0.0000000000000000' > /lattice/slots/212
echo '0.0000000000000000' > /lattice/slots/213
echo '0.0000000000000000' > /lattice/slots/214
echo '0.0000000000000000' > /lattice/slots/215
echo '0.0000000000000000' > /lattice/slots/216
echo '0.0000000000000000' > /lattice/slots/217
echo '0.0000000000000000' > /lattice/slots/218
echo '0.0000000000000000' > /lattice/slots/219
echo '0.0000000000000000' > /lattice/slots/220
echo '0.0000000000000000' > /lattice/slots/221
echo '0.0000000000000000' > /lattice/slots/222
echo '0.0000000000000000' > /lattice/slots/223
echo '0.0000000000000000' > /lattice/slots/224
echo '0.0000000000000000' > /lattice/slots/225
echo '0.0000000000000000' > /lattice/slots/226
echo '0.0000000000000000' > /lattice/slots/227
echo '0.0000000000000000' > /lattice/slots/228
echo '0.0000000000000000' > /lattice/slots/229
echo '0.0000000000000000' > /lattice/slots/230
echo '0.0000000000000000' > /lattice/slots/231
echo '0.0000000000000000' > /lattice/slots/232
echo '0.0000000000000000' > /lattice/slots/233
echo '0.0000000000000000' > /lattice/slots/234
echo '0.0000000000000000' > /lattice/slots/235
echo '0.0000000000000000' > /lattice/slots/236
echo '0.0000000000000000' > /lattice/slots/237
echo '0.0000000000000000' > /lattice/slots/238
echo '0.0000000000000000' > /lattice/slots/239
echo '0.0000000000000000' > /lattice/slots/240
echo '0.0000000000000000' > /lattice/slots/241
echo '0.0000000000000000' > /lattice/slots/242
echo '0.0000000000000000' > /lattice/slots/243
echo '0.0000000000000000' > /lattice/slots/244
echo '0.0000000000000000' > /lattice/slots/245
echo '0.0000000000000000' > /lattice/slots/246
echo '0.0000000000000000' > /lattice/slots/247
echo '0.0000000000000000' > /lattice/slots/248
echo '0.0000000000000000' > /lattice/slots/249
echo '0.0000000000000000' > /lattice/slots/250
echo '0.0000000000000000' > /lattice/slots/251
echo '0.0000000000000000' > /lattice/slots/252
echo '0.0000000000000000' > /lattice/slots/253
echo '0.0000000000000000' > /lattice/slots/254
echo '0.0000000000000000' > /lattice/slots/255
chown -R slot4096:slot4096 /lattice/slots
echo '[lattice] /lattice/slots/ written.'

# -- 13. MOTD --
cat > /etc/motd << 'EOMOTD'
+--------------------------------------------------------------+
| Slot4096 Lattice-Powered Alpine Linux                        |
| seed : 0xba8ddca35827e77f                               |
| slots: 4096   steps: 0      nice: -20                        |
| host : phi4096-00000000                                 |
| tz   : Etc/GMT+11                                       |
| user : slot4096  uid: 1000   umask: 0002                     |
| lim  : nofile=1024    hist=500    tmout=300 s               |
| kern : swap=0    pid_max=32768     conn=128    aslr=0       |
| pkgs :  curl bash                                           |
+--------------------------------------------------------------+
EOMOTD

# -- 14. Launch: su into slot4096 lattice user --
cat /etc/motd
echo '[lattice] OS fully initialised -- resonance substrate active'
exec su - slot4096 -s /bin/bash 2>/dev/null || exec su - slot4096
