#!/bin/sh
# lattice_init.sh -- generated by Slot4096 resonance engine
# Every parameter below was derived from the live phi-lattice state.
# This script IS the OS boot sequence.

# -- 1. Entropy: feed all 4096 slot values into /dev/urandom --
if [ -f '/lattice/entropy.bin' ]; then
  dd if='/lattice/entropy.bin' of=/dev/urandom bs=4096 2>/dev/null
  echo "[lattice] Entropy: $(wc -c < '/lattice/entropy.bin') bytes -> /dev/urandom"
fi

# -- 2. Hostname (phi-fold of slots[0..3]) --
hostname 'phi4096-e6c1d37d'
echo 'phi4096-e6c1d37d' > /etc/hostname
echo '[lattice] Hostname:  phi4096-e6c1d37d'

# -- 3. Timezone (slot[16] -> Etc/GMT-5) --
ln -sf /usr/share/zoneinfo/Etc/GMT-5 /etc/localtime 2>/dev/null
echo 'Etc/GMT-5' > /etc/timezone
echo '[lattice] Timezone:  Etc/GMT-5'

# -- 4. APK mirror (slot[4] -> alpine.global.ssl.fastly.net) --
cat > /etc/apk/repositories << 'EOAPK'
https://alpine.global.ssl.fastly.net/alpine/latest-stable/main
https://alpine.global.ssl.fastly.net/alpine/latest-stable/community
EOAPK
echo '[lattice] APK mirror: alpine.global.ssl.fastly.net'

# -- 5. Packages (slots[5..15] bit-select) --
echo '[lattice] Installing: python3 curl htop bash vim jq git openssl ncurses file'
apk update -q 2>/dev/null && apk add -q python3 curl htop bash vim jq git openssl ncurses file 2>/dev/null
echo '[lattice] Packages ready.'

# -- 6. Process priority (slot[17] -> nice -11) --
renice -11 $$ >/dev/null 2>&1
echo '[lattice] Nice: -11'

# -- 7. slot4096 user (slot[18] -> UID 6561) --
addgroup -g 6561 slot4096 2>/dev/null
adduser -u 6561 -G slot4096 -h /home/slot4096 -s /bin/bash -D slot4096 2>/dev/null
mkdir -p /home/slot4096
chown slot4096:slot4096 /home/slot4096
echo '[lattice] User: slot4096 uid=6561'

# -- 8. Profile: export LATTICE_* + ulimit/umask to all shells --
mkdir -p /etc/profile.d
cat > /etc/profile.d/lattice.sh << 'EOPROFILE'
export LATTICE_N=4096
export LATTICE_STEPS=50
export LATTICE_SEED=0x1315ccefde4ba979
export LATTICE_HOSTNAME=phi4096-e6c1d37d
export LATTICE_MIRROR=alpine.global.ssl.fastly.net
export LATTICE_TZ=Etc/GMT-5
export LATTICE_NICE=-11
export LATTICE_UID=6561
export LATTICE_NOFILE=39936
export LATTICE_UMASK=0022
export LATTICE_HISTSIZE=2624
export LATTICE_TMOUT=2339
umask 0022
ulimit -n 39936 2>/dev/null
export HISTSIZE=2624
export HISTFILESIZE=5248
export TMOUT=2339
export PS1='\[\033[1;35m\]slot4096@phi4096-e6c1d37d:\[\033[1;32m\]\w\[\033[0m\]$ '
EOPROFILE

# -- 9. ~/.bashrc for slot4096 --
cat > /home/slot4096/.bashrc << 'EOBASHRC'
. /etc/profile.d/lattice.sh
alias ls='ls --color=auto'
alias ll='ls -la'
alias lattice='cat /lattice/state.env'
alias slots='ls /lattice/slots/ | head -32'
export HISTFILE=/home/slot4096/.bash_history
EOBASHRC
cp /home/slot4096/.bashrc /home/slot4096/.bash_profile
chown slot4096:slot4096 /home/slot4096/.bashrc /home/slot4096/.bash_profile
echo '[lattice] ~/.bashrc written for slot4096'

# -- 10. /etc/issue --
printf '\nSlot4096 Lattice-Powered Alpine Linux\n  host: phi4096-e6c1d37d  seed: 0x1315ccefde4ba979\n  slots: 4096  steps: 50  nice: -11  uid: 6561\n\n' > /etc/issue
echo '[lattice] /etc/issue written'

# -- 11. /etc/os-release --
cat > /etc/os-release << 'EOOSREL'
NAME="Slot4096 Alpine Linux"
ID=alpine
PRETTY_NAME="Slot4096 Lattice-Powered Alpine Linux"
LATTICE_SEED=0x1315ccefde4ba979
LATTICE_HOST=phi4096-e6c1d37d
LATTICE_SLOTS=4096
LATTICE_STEPS=50
EOOSREL
echo '[lattice] /etc/os-release written'

# -- 12. /lattice/slots/ : slot values as files --
mkdir -p /lattice/slots
echo '0.6180339887498949' > /lattice/slots/0
echo '0.6180339887498949' > /lattice/slots/1
echo '0.6180430326315713' > /lattice/slots/2
echo '0.6180430326315713' > /lattice/slots/3
echo '0.6180395781761612' > /lattice/slots/4
echo '0.6180464870869815' > /lattice/slots/5
echo '0.6180520765132478' > /lattice/slots/6
echo '0.6180486220578376' > /lattice/slots/7
echo '0.6180486220578376' > /lattice/slots/8
echo '0.6180451676024274' > /lattice/slots/9
echo '0.6180512610269457' > /lattice/slots/10
echo '0.6181007503770402' > /lattice/slots/11
echo '0.6180512610269457' > /lattice/slots/12
echo '0.2360377560959113' > /lattice/slots/13
echo '0.6180645748503344' > /lattice/slots/14
echo '0.6181132487141268' > /lattice/slots/15
echo '0.6180598009103702' > /lattice/slots/16
echo '0.2360433455221775' > /lattice/slots/17
echo '0.6180632553657803' > /lattice/slots/18
echo '0.6181217885975512' > /lattice/slots/19
echo '0.6180632553657803' > /lattice/slots/20
echo '0.2360523894038540' > /lattice/slots/21
echo '0.6181678234922354' > /lattice/slots/22
echo '0.6181214771095012' > /lattice/slots/23
echo '0.6180788966702271' > /lattice/slots/24
echo '0.2360564339506959' > /lattice/slots/25
echo '0.2360077600869035' > /lattice/slots/26
echo '0.6181339754465878' > /lattice/slots/27
echo '0.6180831666119393' > /lattice/slots/28
echo '0.2360606177992284' > /lattice/slots/29
echo '0.6181791948549700' > /lattice/slots/30
echo '0.6181339754465878' > /lattice/slots/31
echo '0.6180900755227596' > /lattice/slots/32
echo '0.6180427211435213' > /lattice/slots/33
echo '0.2360237128794003' > /lattice/slots/34
echo '0.6181374299019979' > /lattice/slots/35
echo '0.6180935299781698' > /lattice/slots/36
echo '0.6180461755989315' > /lattice/slots/37
echo '0.6181903737075025' > /lattice/slots/38
echo '0.6181441463026163' > /lattice/slots/39
echo '0.6181025738598462' > /lattice/slots/40
echo '0.6182523613946835' > /lattice/slots/41
echo '0.2360383461873430' > /lattice/slots/42
echo '0.6181486087545305' > /lattice/slots/43
echo '0.6183042972036841' > /lattice/slots/44
echo '0.6180598009103702' > /lattice/slots/45
echo '0.6182130429006176' > /lattice/slots/46
echo '0.2359936307772128' > /lattice/slots/47
echo '0.6181071552896085' > /lattice/slots/48
echo '0.6182638517352661' > /lattice/slots/49
echo '0.2360500290381276' > /lattice/slots/50
echo '0.6181600990951130' > /lattice/slots/51
echo '0.2359526813105428' > /lattice/slots/52
echo '0.6180663983331405' > /lattice/slots/53
echo '0.6182220867822941' > /lattice/slots/54
echo '0.2360082640851555' > /lattice/slots/55
echo '0.6181178301438890' > /lattice/slots/56
echo '0.6182735921253966' > /lattice/slots/57
echo '0.2360635682563865' > /lattice/slots/58
echo '0.6181823378223301' > /lattice/slots/59
echo '0.6183299903863113' > /lattice/slots/60
echo '0.6180769542095730' > /lattice/slots/61
echo '0.6182336506552306' > /lattice/slots/62
echo '0.2360196683325584' > /lattice/slots/63
echo '0.6181423963521642' > /lattice/slots/64
echo '0.6182844594898791' > /lattice/slots/65
echo '0.6180365087411550' > /lattice/slots/66
echo '0.6181935166748627' > /lattice/slots/67
echo '0.2359739120412558' > /lattice/slots/68
echo '0.6180876290638535' > /lattice/slots/69
echo '0.6182443255095111' > /lattice/slots/70
echo '0.2360303431868389' > /lattice/slots/71
echo '0.6181530712064447' > /lattice/slots/72
echo '0.6183007237704259' > /lattice/slots/73
echo '0.6180471835954355' > /lattice/slots/74
echo '0.6182025605565391' > /lattice/slots/75
echo '0.6183558025467866' > /lattice/slots/76
echo '0.6181126257380267' > /lattice/slots/77
echo '0.6182581433311518' > /lattice/slots/78
echo '0.2360398910667674' > /lattice/slots/79
echo '0.6181578451464089' > /lattice/slots/80
echo '0.2359438628237367' > /lattice/slots/81
echo '0.6184587397006376' > /lattice/slots/82
echo '0.6182107889519135' > /lattice/slots/83
echo '0.2360002610846514' > /lattice/slots/84
echo '0.6185241818432288' > /lattice/slots/85
echo '0.6182685066973823' > /lattice/slots/86
echo '0.2360510699192999' > /lattice/slots/87
echo '0.6185694012516110' > /lattice/slots/88
echo '0.6183214505028869' > /lattice/slots/89
echo '0.6180823511256373' > /lattice/slots/90
echo '0.2358629718869008' > /lattice/slots/91
echo '0.6183778487638016' > /lattice/slots/92
echo '0.6181277630442215' > /lattice/slots/93
echo '0.2359137807215492' > /lattice/slots/94
echo '0.6184286575984501' > /lattice/slots/95
echo '0.6181807068497260' > /lattice/slots/96
echo '0.2359688594979099' > /lattice/slots/97
echo '0.6184940997410413' > /lattice/slots/98
echo '0.6182383510628409' > /lattice/slots/99
echo '0.2360209878171124' > /lattice/slots/100
echo '0.6185392456170695' > /lattice/slots/101
echo '0.6182912948683454' > /lattice/slots/102
echo '0.6180511420490977' > /lattice/slots/103
echo '0.2358328897847133' > /lattice/slots/104
echo '0.6183472626633622' > /lattice/slots/105
echo '0.6180971769437820' > /lattice/slots/106
echo '0.2358831946211097' > /lattice/slots/107
echo '0.6183980714980106' > /lattice/slots/108
echo '0.6181501207492865' > /lattice/slots/109
echo '0.2359387773957224' > /lattice/slots/110
echo '0.6184639441064999' > /lattice/slots/111
echo '0.6182082689606534' > /lattice/slots/112
echo '0.2359991341102994' > /lattice/slots/113
echo '0.6185091635148821' > /lattice/slots/114
echo '0.6182612127661580' > /lattice/slots/115
echo '0.2360542128866601' > /lattice/slots/116
echo '0.6185621073203866' > /lattice/slots/117
echo '0.6183176110270727' > /lattice/slots/118
echo '0.6180653903366364' > /lattice/slots/119
echo '0.6186198250658554' > /lattice/slots/120
echo '0.6183774637433976' > /lattice/slots/121
echo '0.6181204691129971' > /lattice/slots/122
echo '0.2359100147780890' > /lattice/slots/123
echo '0.6184333580060604' > /lattice/slots/124
echo '0.6181803218293220' > /lattice/slots/125
echo '0.2359664130390038' > /lattice/slots/126
echo '0.6184777619281405' > /lattice/slots/127
echo '0.6182310116861225' > /lattice/slots/128
echo '0.2360228112999185' > /lattice/slots/129
echo '0.6185319062403511' > /lattice/slots/130
echo '0.6182862094403312' > /lattice/slots/131
echo '0.6180348042361969' > /lattice/slots/132
echo '0.6185896239858200' > /lattice/slots/133
echo '0.6183472626633622' > /lattice/slots/134
echo '0.6180993119146381' > /lattice/slots/135
echo '0.2358797401656996' > /lattice/slots/136
echo '0.6184023414397228' > /lattice/slots/137
echo '0.6181501207492865' > /lattice/slots/138
echo '0.2359361384266143' > /lattice/slots/139
echo '0.6184475608481050' > /lattice/slots/140
echo '0.6182005445635310' > /lattice/slots/141
echo '0.2359866357732128' > /lattice/slots/142
echo '0.6185014391177597' > /lattice/slots/143
echo '0.6182560083602957' > /lattice/slots/144
echo '0.2360380346992930' > /lattice/slots/145
echo '0.6185594229057845' > /lattice/slots/146
echo '0.6183164386072266' > /lattice/slots/147
echo '0.6180684878585025' > /lattice/slots/148
echo '0.6186123667112891' > /lattice/slots/149
echo '0.6183644159625650' > /lattice/slots/150
echo '0.6181199196692511' > /lattice/slots/151
echo '0.6186687649722038' > /lattice/slots/152
echo '0.6184167367919695' > /lattice/slots/153
echo '0.6181709210141015' > /lattice/slots/154
echo '0.2359567587420530' > /lattice/slots/155
echo '0.6184808594500066' > /lattice/slots/156
echo '0.6182273192750163' > /lattice/slots/157
echo '0.2360077600869035' > /lattice/slots/158
echo '0.2357598093381794' > /lattice/slots/159
echo '0.6182837175359310' > /lattice/slots/160
echo '0.6188291083834736' > /lattice/slots/161
echo '0.2358196620545043' > /lattice/slots/162
echo '0.6183345263705795' > /lattice/slots/163
echo '0.6188910960706546' > /lattice/slots/164
echo '0.2358747408308650' > /lattice/slots/165
echo '0.6183859581813280' > /lattice/slots/166
echo '0.6189425278814031' > /lattice/slots/167
echo '0.2359261726416135' > /lattice/slots/168
echo '0.6184500808393651' > /lattice/slots/169
echo '0.6189940332245056' > /lattice/slots/170
echo '0.2359776779847160' > /lattice/slots/171
echo '0.6185017051603157' > /lattice/slots/172
echo '0.6190505504632684' > /lattice/slots/173
echo '0.2360432265443295' > /lattice/slots/174
echo '0.6185525139949641' > /lattice/slots/175
echo '0.6191104031795933' > /lattice/slots/176
echo '0.6180544775266599' > /lattice/slots/177
echo '0.6186089122558789' > /lattice/slots/178
echo '0.2356012894097157' > /lattice/slots/179
echo '0.6181074213321645' > /lattice/slots/180
echo '0.6186653105167936' > /lattice/slots/181
echo '0.2356454882607681' > /lattice/slots/182
echo '0.6181672740484894' > /lattice/slots/183
echo '0.6187161193514421' > /lattice/slots/184
echo '0.2356997641116525' > /lattice/slots/185
echo '0.6182223528248501' > /lattice/slots/186
echo '0.6187677436723926' > /lattice/slots/187
echo '0.2357574818571213' > /lattice/slots/188
echo '0.6182744811440526' > /lattice/slots/189
echo '0.6188323703286818' > /lattice/slots/190
echo '0.2358104256626259' > /lattice/slots/191
echo '0.6183386038020897' > /lattice/slots/192
echo '0.6188826751650782' > /lattice/slots/193
echo '0.2358663073644629' > /lattice/slots/194
echo '0.6183902281230402' > /lattice/slots/195
echo '0.6189390734259930' > /lattice/slots/196
echo '0.2359282950516439' > /lattice/slots/197
echo '0.6184402214713867' > /lattice/slots/198
echo '0.6189954716869077' > /lattice/slots/199
echo '0.2359742235293059' > /lattice/slots/200
echo '0.6184954927579493' > /lattice/slots/201
echo '0.6190499274871684' > /lattice/slots/202
echo '0.2360279828211125' > /lattice/slots/203
echo '0.6185484365634539' > /lattice/slots/204
echo '0.6190972818664067' > /lattice/slots/205
echo '0.6180559895214159' > /lattice/slots/206
echo '0.6186048348243687' > /lattice/slots/207
echo '0.2355845211309169' > /lattice/slots/208
echo '0.6181049748732583' > /lattice/slots/209
echo '0.6186556436590172' > /lattice/slots/210
echo '0.2356486437889540' > /lattice/slots/211
echo '0.6181579186787629' > /lattice/slots/212
echo '0.6187205818033563' > /lattice/slots/213
echo '0.2356994526236025' > /lattice/slots/214
echo '0.6182143169396777' > /lattice/slots/215
echo '0.6187666166980406' > /lattice/slots/216
echo '0.2357502614582510' > /lattice/slots/217
echo '0.6182763046268587' > /lattice/slots/218
echo '0.6188216954744012' > /lattice/slots/219
echo '0.2358122491454320' > /lattice/slots/220
echo '0.6183220280334929' > /lattice/slots/221
echo '0.6188772782490140' > /lattice/slots/222
echo '0.2358656969491886' > /lattice/slots/223
echo '0.6183757873252995' > /lattice/slots/224
echo '0.6189302220545185' > /lattice/slots/225
echo '0.2359138668147289' > /lattice/slots/226
echo '0.6184377750124805' > /lattice/slots/227
echo '0.6189866203154333' > /lattice/slots/228
echo '0.2359659951339315' > /lattice/slots/229
echo '0.6184885838471290' > /lattice/slots/230
echo '0.6190374291500818' > /lattice/slots/231
echo '0.2360301177919686' > /lattice/slots/232
echo '0.6185393926817775' > /lattice/slots/233
echo '0.6191027977603190' > /lattice/slots/234
echo '0.6180469456397395' > /lattice/slots/235
echo '0.6185923364872821' > /lattice/slots/236
echo '0.6191480907010551' > /lattice/slots/237
echo '0.6181033439006542' > /lattice/slots/238
echo '0.6186577786298733' > /lattice/slots/239
echo '0.6192010345065597' > /lattice/slots/240
echo '0.6181584226770149' > /lattice/slots/241
echo '0.6187038135245575' > /lattice/slots/242
echo '0.2356935517092862' > /lattice/slots/243
echo '0.6182140054516276' > /lattice/slots/244
echo '0.6187572613283141' > /lattice/slots/245
echo '0.2357464955147908' > /lattice/slots/246
echo '0.6182613598308659' > /lattice/slots/247
echo '0.6188192490154951' > /lattice/slots/248
echo '0.2358028937757055' > /lattice/slots/249
echo '0.6183143036363705' > /lattice/slots/250
echo '0.6188695538518916' > /lattice/slots/251
echo '0.2358531986121020' > /lattice/slots/252
echo '0.6183762913235515' > /lattice/slots/253
echo '0.6189251366265043' > /lattice/slots/254
echo '0.2359191447529452' > /lattice/slots/255
chown -R slot4096:slot4096 /lattice/slots
echo '[lattice] /lattice/slots/ written.'

# -- 13. MOTD --
cat > /etc/motd << 'EOMOTD'
+--------------------------------------------------------------+
| Slot4096 Lattice-Powered Alpine Linux                        |
| seed : 0x1315ccefde4ba979                               |
| slots: 4096   steps: 50     nice: -11                        |
| host : phi4096-e6c1d37d                                 |
| tz   : Etc/GMT-5                                        |
| user : slot4096  uid: 6561   umask: 0022                     |
| lim  : nofile=39936   hist=2624   tmout=2339s               |
| pkgs : python3 curl htop bash vim jq git openssl ncurses file |
+--------------------------------------------------------------+
EOMOTD

# -- 14. Launch: su into slot4096 lattice user --
cat /etc/motd
echo '[lattice] OS fully initialised -- resonance substrate active'
exec su - slot4096 -s /bin/bash 2>/dev/null || exec su - slot4096
